# Generated by Django 4.2.29 on 2026-03-11 22:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'Vista'), ('favorite', 'Favorito'), ('click', 'Clic')], max_length=20, verbose_name='tipo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='fecha')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='courses.course', verbose_name='curso')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'interacción',
                'verbose_name_plural': 'interacciones',
                'ordering': ['-created_at'],
            },
        ),
    ]
