# Generated by Django 4.2.29 on 2026-05-06 05:55

from django.db import migrations, models
import django.db.models.functions.text


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_course_video_url'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='course',
            index=models.Index(fields=['-created_at'], name='course_created_at_desc'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(django.db.models.functions.text.Lower('category'), name='course_category_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(django.db.models.functions.text.Lower('platform'), name='course_platform_lower_idx'),
        ),
        migrations.AddIndex(
            model_name='course',
            index=models.Index(django.db.models.functions.text.Lower('level'), name='course_level_lower_idx'),
        ),
    ]
